version: "3.9"
services:
  product_db:
    image: postgres:14
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5433:5432"]
  order_db:
    image: postgres:14
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5434:5432"]
  customer_db:
    image: postgres:14
    environment:
      POSTGRES_DB: customerdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5435:5432"]

  rabbitmq:
    image: rabbitmq:3-management
    ports: ["5672:5672", "15672:15672"]

  product_service:
    build: ./backend/product_service
    environment:
      DATABASE_URL: postgresql://postgres:postgres@product_db:5432/productdb
      RABBITMQ_HOST: rabbitmq
      AZURE_STORAGE_ACCOUNT_NAME: ${AZURE_STORAGE_ACCOUNT_NAME}
      AZURE_STORAGE_ACCOUNT_KEY: ${AZURE_STORAGE_ACCOUNT_KEY}
      AZURE_STORAGE_CONTAINER: ${AZURE_STORAGE_CONTAINER:-product-images}
    ports: ["8000:8000"]
    depends_on: [product_db, rabbitmq]

  order_service:
    build: ./backend/order_service
    environment:
      DATABASE_URL: postgresql://postgres:postgres@order_db:5432/orderdb
      PRODUCT_SERVICE_URL: http://product_service:8000
      RABBITMQ_HOST: rabbitmq
    ports: ["8001:8000"]
    depends_on: [order_db, rabbitmq, product_service]

  customer_service:
    build: ./backend/customer_service
    environment:
      DATABASE_URL: postgresql://postgres:postgres@customer_db:5432/customerdb
      RABBITMQ_HOST: rabbitmq
    ports: ["8002:8000"]
    depends_on: [customer_db, rabbitmq]

  frontend:
    build: ./frontend
    environment:
      PRODUCT_API_BASE_URL: http://localhost:8000
      ORDER_API_BASE_URL: http://localhost:8001
      CUSTOMER_API_BASE_URL: http://localhost:8002
    ports: ["3000:80"]
    depends_on: [product_service, order_service, customer_service]