apiVersion: v1
kind: Service
metadata: { name: customer-db }
spec:
  type: ClusterIP
  selector: { app: customer-db }
  ports: [{ port: 5432, targetPort: 5432 }]
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: customer-db }
spec:
  replicas: 1
  selector: { matchLabels: { app: customer-db } }
  template:
    metadata: { labels: { app: customer-db } }
    spec:
      containers:
      - name: postgres
        image: postgres:14
        env:
        - { name: POSTGRES_DB, value: customerdb }
        - { name: POSTGRES_USER, value: postgres }
        - { name: POSTGRES_PASSWORD, value: postgres }
        ports: [{ containerPort: 5432 }]
