apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-init
  namespace: sit722
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: create-dbs
          image: postgres:15
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: POSTGRES_PASSWORD
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: POSTGRES_USER
            - name: PGHOST
              value: postgres
          command: ["bash","-lc"]
          args:
            - |
              echo "Waiting for postgres..."
              until pg_isready -h "$PGHOST" -p 5432 -U "$PGUSER"; do sleep 3; done
              psql -h "$PGHOST" -U "$PGUSER" -c "CREATE DATABASE orders;"     || true
              psql -h "$PGHOST" -U "$PGUSER" -c "CREATE DATABASE customers;"  || true