# Template with stringData so you can apply via CI (no base64 needed).
# In prod workflow I’ll show how we inject values.
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: sit722
type: Opaque
stringData:
  AZURE_STORAGE_ACCOUNT_KEY: "__INJECT_AT_DEPLOY__"