apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  AZURE_STORAGE_ACCOUNT_NAME: c2l0NzIycHJvZHN0b3JhZ2U=
  AZURE_STORAGE_ACCOUNT_KEY:  S0lNTFB0dWxIVjJNNCtXOGJxRXhYWTNYaG54RFFqZ0pWMzJENkM3eXVyYWNKUXRpNnpEK3VwMW5CNVlZQk8reEZwcUhxNDFITE5FSStBU3RTczNVaVE9PQ==