# .github/workflows/ci-main.yml  (full job for clarity)
name: CI Main

on:
  push:
    branches: [main]

env:
  ACR_NAME: ${{ secrets.ACR_NAME }}
  ACR: ${{ secrets.ACR_NAME }}.azurecr.io
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build & push images to ACR
        run: |
          set -euo pipefail
          az acr login --name "$ACR_NAME"

          # Logical image names (must match what CD sets)
          for s in product-service order-service customer-service frontend; do
            # Map logical name -> folder path
            case "$s" in
              product-service)  ctx="backend/product_service"  ;;
              order-service)    ctx="backend/order_service"    ;;
              customer-service) ctx="backend/customer_service" ;;
              frontend)         ctx="frontend"                 ;;
            esac
            df="$ctx/Dockerfile"

            if [ ! -f "$df" ]; then
              echo "ERROR: Can't find $df for $s"; exit 1
            fi

            echo "Building $s from $df (context=$ctx)"
            docker build -t "$ACR/$s:$IMAGE_TAG" -f "$df" "$ctx"
            docker push "$ACR/$s:$IMAGE_TAG"
          done