name: CI Main
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Build *in ACR* and push with the merge commit SHA tag
      - name: Build & push images to ACR
        run: |
          ACR=${{ secrets.ACR_NAME }}
          SHA=${{ github.sha }}
          for r in product-service order-service customer-service frontend; do
            az acr build -r $ACR -t $ACR.azurecr.io/$r:$SHA $r/
          done